# Generated by Django 6.0.2 on 2026-02-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
